name: Publicar site no GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do repositório
        uses: actions/checkout@v4

      - name: Preparar arquivos do site
        run: |
          mkdir public
          cp -r html/* public/
          cp -r css public/
          cp -r imagens public/
          cp -r js public/

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Fazer upload do site
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
